# enter in S3/LeoFS settings and save as config.yaml
---
s3:
    access_key_id:
    secret_access_key:
    default_bucket:
    endpoint: http://localhost:8080
    tls: False
api_url: http://localhost:3002/api/fileProcessing
