# enter in S3/LeoFS settings and save as config.yaml
---
s3:
    access_key_id:
    secret_access_key:
    default_bucket:
    endpoint: http://localhost:8080
    tls: False

api_url: http://localhost:3002/api/fileProcessing

# Setup classifier_pipeline [https://github.com/TheCacophonyProject/classifier-pipeline]
classify_command_dir: "/path/to/classifier_pipeline"
# Relative paths in this command are relative from the classify_command_dir. Should be run using the classifier_pipeline python3.6 virtial environment.
classify_command: "venv/bin/python classify.py --enable-preview --meta-to-stdout -s {source_dir} -o {output_dir} {source}"
